#!/usr/bin/env python3
"""
静态网站生成器 —— 从 papers/ 目录生成个人学术主页。

用法：
    python website/build.py              # 构建全站
    python website/build.py --serve      # 构建 + 本地预览
    python website/build.py --lang en    # 仅英文版

输出: website/public/
"""

import os, re, sys, json, shutil, subprocess
from pathlib import Path
from datetime import date
from collections import defaultdict

import yaml
import markdown as md_lib
from jinja2 import Environment, FileSystemLoader

# ─── 路径 ───────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
WEBSITE_DIR = ROOT / "website"
TEMPLATES_DIR = WEBSITE_DIR / "templates"
STATIC_DIR = WEBSITE_DIR / "static"
PUBLIC_DIR = WEBSITE_DIR / "public"
PAPERS_DIR = ROOT / "papers"
CONFIG_PATH = WEBSITE_DIR / "config.yml"

MD = md_lib.Markdown(extensions=["fenced_code", "codehilite", "tables", "nl2br"])

# ─── 翻译字典 ───────────────────────────────────────────────
T = {
    "zh": {
        "lang_label": "中",
        "switch_label": "EN",
        "switch_url": "/en/",
        "site_built_by": "由 AOS 自动生成",
        "nav": {
            "index": "首页",
            "publications": "论文",
            "projects": "项目",
        },
        "index": {
            "welcome": "欢迎来到我的学术主页",
            "latest": "最新论文",
            "projects": "进行中项目",
            "all_projects": "查看全部项目 →",
            "no_projects": "暂无进行中的项目",
            "no_publications": "暂无论文",
        },
        "publications": {
            "title": "论文",
            "desc": "已发表论文列表",
            "no_papers": "暂无已发表论文。",
            "authors": "作者",
            "journal": "期刊",
            "year": "年份",
            "doi": "DOI",
        },
        "research": {
            "title": "研究领域",
            "desc": "领域 × 核心问题 矩阵，每个格子链接到对应项目。",
            "empty_cell": "—",
            "no_matrix": "矩阵尚未配置。请先在 matrix.md 中填写研究领域与核心问题。",
        },
        "outputs": {
            "title": "学术产出",
            "desc": "论文 · 软件 · 结果",
            "papers": "📄 已发表论文",
            "papers_desc": "同行评议的期刊论文、会议论文和预印本。",
            "no_papers": "暂无已发表论文。",
            "filter_type": "按类型筛选",
            "all": "全部",
            "authors": "作者",
            "journal": "期刊",
            "year": "年份",
            "doi": "DOI",
        },
        "projects": {
            "title": "项目",
            "desc": "学术项目管线：想法 → 进行中 → 已完成。",
            "ideas": "💡 想法",
            "active": "🔬 进行中",
            "completed": "✅ 已完成",
            "no_ideas": "暂无想法",
            "no_active": "暂无进行中的项目",
            "no_completed": "暂无已完成的项目",
            "status": "状态",
            "domain": "领域",
            "problem": "问题",
            "back": "← 返回项目列表",
        },
        "skills": {
            "title": "能力",
            "desc": "学术技能树，每条技能关联证据。",
            "no_skills": "技能树尚未配置。请在 competencies/skill-tree.md 中填写。",
            "evidence": "证据",
            "no_evidence": "暂无证据",
            "rating": "评级",
            "last_reviewed": "最近回顾",
        },
        "atoms": {
            "title": "知识库",
            "desc": "全部产出原子——最小可重组知识单元。",
            "filter_type": "按类型",
            "filter_tag": "按标签",
            "all": "全部",
            "no_atoms": "知识库为空。在 knowledge/atoms/ 下创建原子后自动展示。",
            "back": "← 返回知识库",
            "type_label": "类型",
            "project": "项目",
            "status": "状态",
            "created": "创建日期",
            "source": "来源",
            "tags": "标签",
        },
        "footer": {
            "copyright": f"© {date.today().year} · 由 AOS 驱动",
        },
        "atom_type_names": {
            "gap": "研究缺口",
            "method": "方法",
            "result": "结果",
            "insight": "洞察",
            "compute": "计算",
        },
        "project_status_names": {
            "idea": "💡 想法",
            "active": "🔬 进行中",
            "writing": "✍️ 撰写中",
            "submitted": "📤 已提交",
            "published": "✅ 已发表",
        },
        "skill_level_names": {
            "L1": "了解",
            "L2": "能做",
            "L3": "熟练",
            "L4": "精通",
        },
    },
    "en": {
        "lang_label": "EN",
        "switch_label": "中",
        "switch_url": "/",
        "site_built_by": "Generated by AOS",
        "nav": {
            "index": "Home",
            "publications": "Publications",
            "projects": "Projects",
        },
        "index": {
            "welcome": "Welcome to My Academic Homepage",
            "latest": "Latest Publications",
            "projects": "Active Projects",
            "all_projects": "View All Projects →",
            "no_projects": "No active projects",
            "no_publications": "No publications yet",
        },
        "publications": {
            "title": "Publications",
            "desc": "Peer-reviewed publications",
            "no_papers": "No publications yet.",
            "authors": "Authors",
            "journal": "Journal",
            "year": "Year",
            "doi": "DOI",
        },
        "research": {
            "title": "Research",
            "desc": "Domain × Problem matrix. Each cell links to a project.",
            "empty_cell": "—",
            "no_matrix": "Matrix not configured. Fill in matrix.md first.",
        },
        "outputs": {
            "title": "Outputs",
            "desc": "Papers · Software · Results",
            "papers": "📄 Publications",
            "papers_desc": "Peer-reviewed journal articles, conference papers, and preprints.",
            "no_papers": "No publications yet. Create entries in knowledge/publications/ to populate.",
            "software": "🛠️ Software",
            "software_desc": "Open-source academic tools, libraries, and applications.",
            "no_software": "No software yet. Create entries in knowledge/software/ to populate.",
            "research": "🔬 Results",
            "research_desc": "Method components and experimental results from the AOS knowledge base.",
            "no_research": "No results yet.",
            "filter_type": "Filter by type",
            "all": "All",
            "authors": "Authors",
            "journal": "Journal",
            "year": "Year",
            "doi": "DOI",
            "repo": "Repository",
            "language": "Language",
            "license": "License",
            "status": "Status",
        },
        "projects": {
            "title": "Projects",
            "desc": "Academic project pipeline: Ideas → Active → Completed.",
            "ideas": "💡 Ideas",
            "active": "🔬 Active",
            "completed": "✅ Completed",
            "no_ideas": "No ideas yet",
            "no_active": "No active projects",
            "no_completed": "No completed projects",
            "status": "Status",
            "domain": "Domain",
            "problem": "Problem",
            "back": "← Back to Projects",
        },
        "skills": {
            "title": "Skills",
            "desc": "Academic skill tree. Each skill is backed by evidence.",
            "no_skills": "Skill tree not configured. Fill in competencies/skill-tree.md.",
            "evidence": "Evidence",
            "no_evidence": "No evidence yet",
            "rating": "Rating",
            "last_reviewed": "Last reviewed",
        },
        "atoms": {
            "title": "Knowledge Base",
            "desc": "All output atoms — the smallest recombinable knowledge units.",
            "filter_type": "By Type",
            "filter_tag": "By Tag",
            "all": "All",
            "no_atoms": "Knowledge base is empty. Create atoms in knowledge/atoms/.",
            "back": "← Back to Knowledge Base",
            "type_label": "Type",
            "project": "Project",
            "status": "Status",
            "created": "Created",
            "source": "Source",
            "tags": "Tags",
        },
        "footer": {
            "copyright": f"© {date.today().year} · Powered by AOS",
        },
        "atom_type_names": {
            "gap": "Gap",
            "method": "Method",
            "result": "Result",
            "insight": "Insight",
            "compute": "Compute",
        },
        "project_status_names": {
            "idea": "💡 Idea",
            "active": "🔬 Active",
            "writing": "✍️ Writing",
            "submitted": "📤 Submitted",
            "published": "✅ Published",
        },
        "skill_level_names": {
            "L1": "Aware",
            "L2": "Competent",
            "L3": "Proficient",
            "L4": "Expert",
        },
    },
}

# ─── 解析工具 ───────────────────────────────────────────────

def parse_front_matter(filepath: str) -> dict | None:
    """从 Markdown 文件提取 YAML front-matter。"""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return None
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n?", content, re.DOTALL)
    if not match:
        # 也匹配无尾部换行的文件
        match = re.match(r"^---\s*\n(.*?)\n---\s*$", content, re.DOTALL)
    if not match:
        return None
    try:
        return yaml.safe_load(match.group(1))
    except yaml.YAMLError:
        return None


def parse_body(filepath: str) -> str:
    """提取 front-matter 之后的正文。"""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    match = re.match(r"^---\s*\n.*?\n---\s*\n", content, re.DOTALL)
    return content[match.end():].strip() if match else content.strip()


def md_to_html(text: str) -> str:
    """Markdown → HTML。"""
    if not text:
        return ""
    return MD.reset().convert(text)


# ─── 加载器 ─────────────────────────────────────────────────

def load_config() -> dict:
    """加载 website/config.yml。"""
    if not CONFIG_PATH.exists():
        print(f"[WARN] 配置文件不存在: {CONFIG_PATH}，使用默认值")
        return {"site": {"title_zh": "学术主页", "title_en": "Academic Homepage"},
                "author": {}, "social": {}, "theme": {}, "nav": [], "homepage": {}}
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_publications() -> list[dict]:
    """从 papers/ 加载论文（跳过 _active、_template、无 index.md 的目录）。"""
    pubs = []
    if not PAPERS_DIR.is_dir():
        return pubs
    for paper_dir in sorted(PAPERS_DIR.iterdir()):
        if not paper_dir.is_dir() or paper_dir.name.startswith("_"):
            continue
        idx = paper_dir / "index.md"
        if not idx.exists():
            continue
        fm = parse_front_matter(str(idx))
        if not fm:
            continue
        pubs.append({
            "id": fm.get("id", paper_dir.name),
            "title": fm.get("title", paper_dir.name),
            "type": fm.get("type", "journal"),
            "status": fm.get("status", "published"),
            "authors": fm.get("authors", []),
            "journal": fm.get("journal", ""),
            "year": fm.get("year", ""),
            "volume": fm.get("volume", ""),
            "issue": fm.get("issue", ""),
            "pages": fm.get("pages", ""),
            "publisher": fm.get("publisher", ""),
            "doi": fm.get("doi", ""),
            "arxiv": fm.get("arxiv", ""),
            "abstract": fm.get("abstract", ""),
            "tags": fm.get("tags", []),
        })
    return pubs


def load_software() -> list[dict]:
    """占位：软体项目（暂不展示，直接从 papers/ 管理）。"""
    return []


def load_skill_tree() -> dict:
    """占位：技能树（暂不展示）。"""
    return {}


def load_matrix() -> dict | None:
    """占位：研究矩阵（暂时不需要）。"""
    return None


def load_projects() -> dict:
    """从 papers/_active/ 加载进行中的项目。"""
    projects = {"active": [], "completed": [], "ideas": []}
    active_dir = PAPERS_DIR / "_active"
    if not active_dir.is_dir():
        return projects

    for proj_dir in sorted(active_dir.iterdir()):
        if not proj_dir.is_dir():
            continue
        idx = proj_dir / "index.md"
        if not idx.exists():
            continue
        fm = parse_front_matter(str(idx))
        if not fm:
            continue
        body = parse_body(str(idx))

        # 扫描报告和数据目录
        drafts_dir = proj_dir / "drafts"
        reports = sorted([f.name for f in drafts_dir.glob("report-*.html")]) if drafts_dir.is_dir() else []
        has_data_dir = (proj_dir / "data").is_dir()

        proj = {
            "id": fm.get("id", proj_dir.name),
            "title": fm.get("title", proj_dir.name),
            "status": fm.get("status", "active"),
            "domain": fm.get("domain", ""),
            "problem": fm.get("problem", ""),
            "description": body,
            "description_html": md_to_html(body),
            "url": f"/projects/{proj_dir.name}/",
            "dir_name": proj_dir.name,
            "reports": reports,
            "has_data_dir": has_data_dir,
        }
        projects["active"].append(proj)

    return projects


def _project_status_name(status: str, lang: str) -> str:
    """项目状态 → 可读名称。"""
    names = {
        "idea": ("💡 想法", "💡 Idea"),
        "active": ("🔬 进行中", "🔬 Active"),
        "writing": ("✍️ 撰写中", "✍️ Writing"),
        "submitted": ("📤 已提交", "📤 Submitted"),
        "published": ("✅ 已发表", "✅ Published"),
    }
    m = names.get(status)
    return m[0] if m and lang == "zh" else (m[1] if m else status)


# ─── 页面构建器 ─────────────────────────────────────────────

def build_site(lang: str, config: dict, skill_tree: dict,
               matrix: dict | None, projects: dict,
               env: Environment) -> int:
    """构建指定语言版本的全站。返回生成的文件数。"""
    t = T.get(lang, T["zh"])
    pages_created = 0
    is_primary = lang == config.get("site", {}).get("lang_primary", "zh")
    prefix = "" if is_primary else f"{lang}/"

    mkdir = lambda p: (PUBLIC_DIR / p).mkdir(parents=True, exist_ok=True)

    # 基础上下文
    from urllib.parse import urlparse
    parsed = urlparse(config.get("site", {}).get("base_url", ""))
    root_path = parsed.path.rstrip("/") + "/"

    ctx = {
        "lang": lang,
        "lang_other": t["switch_label"],
        "lang_other_url": t["switch_url"],
        "config": config,
        "t": t,
        "current_year": date.today().year,
        "is_primary": is_primary,
        "prefix": prefix,
        "root": root_path,
    }

    # ── 首页 ──
    mkdir(prefix)
    pubs_data = load_publications()
    index_ctx = {**ctx,
        "page_id": "index",
        "latest_publications": pubs_data[:config.get("homepage", {}).get("show_latest_pubs", 5)],
        "active_projects": projects.get("active", [])[:config.get("homepage", {}).get("show_featured_projects", 3)],
    }
    _write_page("index.html", index_ctx, env, PUBLIC_DIR / prefix / "index.html")
    pages_created += 1

    # ── 学术产出（论文列表） ──
    mkdir(prefix + "publications")
    outputs_ctx = {**ctx, "page_id": "publications",
        "publications": pubs_data,
        "pub_types": sorted(set(p["type"] for p in pubs_data))}
    _write_page("publications.html", outputs_ctx, env, PUBLIC_DIR / prefix / "publications" / "index.html")
    pages_created += 1

    # ── 项目 ──
    mkdir(prefix + "projects")
    projs_ctx = {**ctx, "page_id": "projects", "projects": projects}
    _write_page("projects.html", projs_ctx, env, PUBLIC_DIR / prefix / "projects" / "index.html")
    pages_created += 1

    # 单个项目详情页
    for bucket_key in ("active",):
        for proj in projects.get(bucket_key, []):
            proj_dir_name = proj["id"]
            mkdir(prefix + f"projects/{proj_dir_name}")
            proj_ctx = {**ctx, "page_id": "project", "project": proj,
                "bucket_key": bucket_key}
            _write_page("project-single.html", proj_ctx, env,
                        PUBLIC_DIR / prefix / "projects" / proj_dir_name / "index.html")
            pages_created += 1

            # 复制项目报告 HTML 和 data/ 图片到网站输出
            _copy_project_assets(proj, prefix)

    return pages_created


def _copy_project_assets(proj: dict, prefix: str):
    """复制项目的报告 HTML 和 data/ 目录到网站输出。"""
    proj_src = PAPERS_DIR / "_active" / proj["dir_name"]
    proj_dst = PUBLIC_DIR / prefix / "projects" / proj["id"]
    proj_dst.mkdir(parents=True, exist_ok=True)

    # 复制 report-*.html（来自 drafts/）
    drafts_dir = proj_src / "drafts"
    if drafts_dir.is_dir():
        for rpt in drafts_dir.glob("report-*.html"):
            shutil.copy2(str(rpt), str(proj_dst / rpt.name))
            print(f"     📄 报告: {proj['dir_name']}/{rpt.name}")

    # 复制 data/ 目录（图片等）
    data_src = proj_src / "data"
    if data_src.is_dir():
        data_dst = proj_dst / "data"
        shutil.copytree(str(data_src), str(data_dst), dirs_exist_ok=True)
        n_files = len(list(data_dst.rglob("*")))
        print(f"     🖼️  图片: {proj['id']}/data/ ({n_files} 个文件)")


def _write_page(template_name: str, context: dict, env: Environment, output_path: Path):
    """渲染模板并写入文件。"""
    try:
        template = env.get_template(template_name)
        html = template.render(**context)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")
    except Exception as e:
        print(f"[ERROR] 渲染 {template_name} → {output_path}: {e}")
        import traceback
        traceback.print_exc()


# ─── 主入口 ─────────────────────────────────────────────────

def main():
    args = set(sys.argv[1:])
    serve = "--serve" in args
    lang_filter = None
    for a in args:
        if a.startswith("--lang="):
            lang_filter = a.split("=", 1)[1]

    print("=" * 56)
    print("  Website Builder")
    print("=" * 56)

    # 1. 加载配置
    config = load_config()
    print(f"  📄 配置已加载")

    # 2. 加载数据
    skill_tree = load_skill_tree()
    matrix = load_matrix()
    projects = load_projects()

    pubs_data = load_publications()
    print(f"  📄 论文: {len(pubs_data)}")
    print(f"  📁 进行中项目: {len(projects.get('active', []))}")

    # 3. 清理输出目录
    if PUBLIC_DIR.exists():
        shutil.rmtree(PUBLIC_DIR)
    PUBLIC_DIR.mkdir(parents=True)

    # 4. 复制静态资源
    static_target = PUBLIC_DIR / "static"
    if STATIC_DIR.exists():
        shutil.copytree(STATIC_DIR, static_target, dirs_exist_ok=True)
    print(f"  🎨 静态资源已复制")

    # 5. 设置 Jinja2
    env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))
    env.globals["resolve_project_status_name"] = _project_status_name
    env.globals["resolve_atom_type_name"] = lambda t, lang: {"journal": "Journal", "conference": "Conference", "preprint": "Preprint"}.get(t, t)

    # 6. 构建各语言版本
    languages = ["zh", "en"] if not lang_filter else [lang_filter]
    total_pages = 0
    for lang in languages:
        print(f"\n  🌐 构建: {'中文' if lang == 'zh' else 'English'} ({lang})")
        n = build_site(lang, config, skill_tree, matrix, projects, env)
        total_pages += n
        print(f"     → {n} 个页面")

    print(f"\n  📊 总计: {total_pages} 个页面")
    print(f"  📂 {PUBLIC_DIR.resolve()}")

    # 7. 写入构建信息
    build_info = {
        "built_at": date.today().isoformat(),
        "langs": languages,
        "pages": total_pages,
        "publications": len(pubs_data),
        "projects": sum(len(v) for v in projects.values()),
    }
    (PUBLIC_DIR / "build-info.json").write_text(
        json.dumps(build_info, indent=2, ensure_ascii=False))

    (PUBLIC_DIR / ".nojekyll").write_text("")
    print("  ✅ 构建完成！")

    if "--watch" in args:
        _start_watch(env)

    if serve:
        print("\n  启动: http://localhost:8000")
        os.chdir(str(PUBLIC_DIR))
        subprocess.run([sys.executable, "-m", "http.server", "8000"])
    else:
        print("  预览: cd website/public && python -m http.server 8000")


def _get_watch_paths() -> list[Path]:
    """返回需要监听的文件列表。"""
    paths = [CONFIG_PATH]
    if TEMPLATES_DIR.is_dir():
        paths.extend(sorted(TEMPLATES_DIR.rglob("*.html")))
    if STATIC_DIR.is_dir():
        paths.extend(sorted(STATIC_DIR.rglob("*")))
    if PAPERS_DIR.is_dir():
        for p in PAPERS_DIR.rglob("index.md"):
            paths.append(p)
    return [p for p in paths if p.exists()]


def _get_mtime_map(paths: list[Path]) -> dict[str, float]:
    return {str(p): p.stat().st_mtime for p in paths}


def _start_watch(env: Environment):
    """文件监听循环。"""
    print("\n  👀 监听中 (Ctrl+C 停止)")
    watch_paths = _get_watch_paths()
    mtime_map = _get_mtime_map(watch_paths)

    import time as _time
    try:
        while True:
            _time.sleep(1.5)
            changed = []
            for p in watch_paths:
                if not p.exists():
                    continue
                current = p.stat().st_mtime
                if abs(current - mtime_map.get(str(p), 0)) > 0.01:
                    changed.append(p)
                    mtime_map[str(p)] = current
            if changed:
                print(f"\n  🔄 {len(changed)} 个文件变化，重建...")
                for c in changed[:3]:
                    print(f"     {c.relative_to(ROOT)}")
                watch_paths = _get_watch_paths()
                mtime_map = _get_mtime_map(watch_paths)
                _do_rebuild()
    except KeyboardInterrupt:
        print("\n  👋 已停止")


def _do_rebuild():
    """执行一次完整重建。"""
    try:
        config = load_config()
        skill_tree = load_skill_tree()
        matrix = load_matrix()
        projects = load_projects()

        if PUBLIC_DIR.exists():
            shutil.rmtree(PUBLIC_DIR)
        PUBLIC_DIR.mkdir(parents=True)

        static_target = PUBLIC_DIR / "static"
        if STATIC_DIR.exists():
            shutil.copytree(STATIC_DIR, static_target, dirs_exist_ok=True)

        env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))
        languages = ["zh", "en"]
        total = 0
        for lang in languages:
            n = build_site(lang, config, skill_tree, matrix, projects, env)
            total += n

        pubs_data = load_publications()
        (PUBLIC_DIR / ".nojekyll").write_text("")
        (PUBLIC_DIR / "build-info.json").write_text(
            json.dumps({"built_at": date.today().isoformat(),
                       "langs": languages, "pages": total,
                       "publications": len(pubs_data),
                       "projects": sum(len(v) for v in projects.values())},
                      indent=2, ensure_ascii=False))
        print(f"  ✅ 重建完成 — {total} 页 ({date.today().isoformat()})")
    except Exception as e:
        print(f"  ❌ 重建失败: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
