#!/usr/bin/env python3
"""
AOS Website Builder — 中英文双语静态网站生成器。

用法：
    cd website/ && python build.py          # 构建全站
    python build.py --serve                 # 构建后启动本地预览 (python -m http.server)
    python build.py --lang en               # 仅构建英文版

输出: website/public/
"""

import os, re, sys, json, shutil, subprocess
from pathlib import Path
from datetime import date
from collections import defaultdict

import yaml
import markdown as md_lib
from jinja2 import Environment, FileSystemLoader

# ─── 路径 ───────────────────────────────────────────────────
ROOT = Path(__file__).resolve().parent.parent
WEBSITE_DIR = ROOT / "website"
TEMPLATES_DIR = WEBSITE_DIR / "templates"
STATIC_DIR = WEBSITE_DIR / "static"
PUBLIC_DIR = WEBSITE_DIR / "public"
ATOMS_DIR = ROOT / "knowledge" / "atoms"
SCRIPTS_DIR = ATOMS_DIR / "scripts"
PROJECTS_DIR = ROOT / "projects"
PUBLICATIONS_DIR = ROOT / "knowledge" / "publications"
SOFTWARE_DIR = ROOT / "knowledge" / "software"
CONFIG_PATH = WEBSITE_DIR / "config.yml"
MATRIX_PATH = ROOT / "matrix.md"
SKILL_TREE_PATH = ROOT / "competencies" / "skill-tree.md"
VOCAB_PATH = ROOT / "knowledge" / "controlled-vocabulary.yml"

MD = md_lib.Markdown(extensions=["fenced_code", "codehilite", "tables", "nl2br"])

# ─── 翻译字典 ───────────────────────────────────────────────
T = {
    "zh": {
        "lang_label": "中",
        "switch_label": "EN",
        "switch_url": "/en/",
        "site_built_by": "由 AOS 自动生成",
        "nav": {
            "index": "首页",
            "research": "研究领域",
            "publications": "产出",
            "projects": "项目",
            "skills": "能力",
            "atoms": "知识库",
        },
        "index": {
            "welcome": "欢迎来到我的学术主页",
            "latest": "最新动态",
            "projects": "进行中项目",
            "all_projects": "查看全部项目 →",
            "view_all_atoms": "查看全部 →",
            "no_projects": "暂无进行中的项目",
            "no_atoms": "暂无原子记录",
        },
        "research": {
            "title": "研究领域",
            "desc": "领域 × 核心问题 矩阵，每个格子链接到对应项目。",
            "empty_cell": "—",
            "no_matrix": "矩阵尚未配置。请先在 matrix.md 中填写研究领域与核心问题。",
        },
        "outputs": {
            "title": "学术产出",
            "desc": "论文 · 软件 · 研究成果",
            "papers": "📄 已发表论文",
            "papers_desc": "同行评议的期刊论文、会议论文和预印本。",
            "no_papers": "暂无已发表论文。在 knowledge/publications/ 下创建后自动展示。",
            "software": "🛠️ 软件开发",
            "software_desc": "开源的学术工具、库和应用程序。",
            "no_software": "暂无软件项目。在 knowledge/software/ 下创建后自动展示。",
            "research": "🔬 研究成果",
            "research_desc": "AOS 知识库中的方法组件和实验结果。",
            "no_research": "暂无研究成果。",
            "filter_type": "按类型筛选",
            "all": "全部",
            "authors": "作者",
            "journal": "期刊",
            "year": "年份",
            "doi": "DOI",
            "repo": "仓库",
            "language": "语言",
            "license": "许可",
            "status": "状态",
        },
        "projects": {
            "title": "项目",
            "desc": "学术项目管线：想法 → 进行中 → 已完成。",
            "ideas": "💡 想法",
            "active": "🔬 进行中",
            "completed": "✅ 已完成",
            "no_ideas": "暂无想法",
            "no_active": "暂无进行中的项目",
            "no_completed": "暂无已完成的项目",
            "status": "状态",
            "domain": "领域",
            "problem": "问题",
            "back": "← 返回项目列表",
        },
        "skills": {
            "title": "能力",
            "desc": "学术技能树，每条技能关联证据。",
            "no_skills": "技能树尚未配置。请在 competencies/skill-tree.md 中填写。",
            "evidence": "证据",
            "no_evidence": "暂无证据",
            "rating": "评级",
            "last_reviewed": "最近回顾",
        },
        "atoms": {
            "title": "知识库",
            "desc": "全部产出原子——最小可重组知识单元。",
            "filter_type": "按类型",
            "filter_tag": "按标签",
            "all": "全部",
            "no_atoms": "知识库为空。在 knowledge/atoms/ 下创建原子后自动展示。",
            "back": "← 返回知识库",
            "type_label": "类型",
            "project": "项目",
            "status": "状态",
            "created": "创建日期",
            "source": "来源",
            "tags": "标签",
        },
        "footer": {
            "copyright": f"© {date.today().year} · 由 AOS 驱动",
        },
        "atom_type_names": {
            "gap": "研究缺口",
            "method": "方法",
            "result": "结果",
            "insight": "洞察",
            "compute": "计算",
        },
        "project_status_names": {
            "idea": "💡 想法",
            "active": "🔬 进行中",
            "writing": "✍️ 撰写中",
            "submitted": "📤 已提交",
            "published": "✅ 已发表",
        },
        "skill_level_names": {
            "L1": "了解",
            "L2": "能做",
            "L3": "熟练",
            "L4": "精通",
        },
    },
    "en": {
        "lang_label": "EN",
        "switch_label": "中",
        "switch_url": "/",
        "site_built_by": "Generated by AOS",
        "nav": {
            "index": "Home",
            "research": "Research",
            "publications": "Outputs",
            "projects": "Projects",
            "skills": "Skills",
            "atoms": "Knowledge",
        },
        "index": {
            "welcome": "Welcome to My Academic Homepage",
            "latest": "Latest Updates",
            "projects": "Active Projects",
            "all_projects": "View All Projects →",
            "view_all_atoms": "View All →",
            "no_projects": "No active projects",
            "no_atoms": "No atoms yet",
        },
        "research": {
            "title": "Research",
            "desc": "Domain × Problem matrix. Each cell links to a project.",
            "empty_cell": "—",
            "no_matrix": "Matrix not configured. Fill in matrix.md first.",
        },
        "outputs": {
            "title": "Outputs",
            "desc": "Papers · Software · Research",
            "papers": "📄 Publications",
            "papers_desc": "Peer-reviewed journal articles, conference papers, and preprints.",
            "no_papers": "No publications yet. Create entries in knowledge/publications/ to populate.",
            "software": "🛠️ Software",
            "software_desc": "Open-source academic tools, libraries, and applications.",
            "no_software": "No software yet. Create entries in knowledge/software/ to populate.",
            "research": "🔬 Research Outputs",
            "research_desc": "Method components and experimental results from the AOS knowledge base.",
            "no_research": "No research outputs yet.",
            "filter_type": "Filter by type",
            "all": "All",
            "authors": "Authors",
            "journal": "Journal",
            "year": "Year",
            "doi": "DOI",
            "repo": "Repository",
            "language": "Language",
            "license": "License",
            "status": "Status",
        },
        "projects": {
            "title": "Projects",
            "desc": "Academic project pipeline: Ideas → Active → Completed.",
            "ideas": "💡 Ideas",
            "active": "🔬 Active",
            "completed": "✅ Completed",
            "no_ideas": "No ideas yet",
            "no_active": "No active projects",
            "no_completed": "No completed projects",
            "status": "Status",
            "domain": "Domain",
            "problem": "Problem",
            "back": "← Back to Projects",
        },
        "skills": {
            "title": "Skills",
            "desc": "Academic skill tree. Each skill is backed by evidence.",
            "no_skills": "Skill tree not configured. Fill in competencies/skill-tree.md.",
            "evidence": "Evidence",
            "no_evidence": "No evidence yet",
            "rating": "Rating",
            "last_reviewed": "Last reviewed",
        },
        "atoms": {
            "title": "Knowledge Base",
            "desc": "All output atoms — the smallest recombinable knowledge units.",
            "filter_type": "By Type",
            "filter_tag": "By Tag",
            "all": "All",
            "no_atoms": "Knowledge base is empty. Create atoms in knowledge/atoms/.",
            "back": "← Back to Knowledge Base",
            "type_label": "Type",
            "project": "Project",
            "status": "Status",
            "created": "Created",
            "source": "Source",
            "tags": "Tags",
        },
        "footer": {
            "copyright": f"© {date.today().year} · Powered by AOS",
        },
        "atom_type_names": {
            "gap": "Gap",
            "method": "Method",
            "result": "Result",
            "insight": "Insight",
            "compute": "Compute",
        },
        "project_status_names": {
            "idea": "💡 Idea",
            "active": "🔬 Active",
            "writing": "✍️ Writing",
            "submitted": "📤 Submitted",
            "published": "✅ Published",
        },
        "skill_level_names": {
            "L1": "Aware",
            "L2": "Competent",
            "L3": "Proficient",
            "L4": "Expert",
        },
    },
}

# ─── 解析工具 ───────────────────────────────────────────────

def parse_front_matter(filepath: str) -> dict | None:
    """从 Markdown 文件提取 YAML front-matter。"""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return None
    match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if not match:
        return None
    try:
        return yaml.safe_load(match.group(1))
    except yaml.YAMLError:
        return None


def parse_body(filepath: str) -> str:
    """提取 front-matter 之后的正文。"""
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    match = re.match(r"^---\s*\n.*?\n---\s*\n", content, re.DOTALL)
    return content[match.end():].strip() if match else content.strip()


def md_to_html(text: str) -> str:
    """Markdown → HTML。"""
    if not text:
        return ""
    return MD.reset().convert(text)


# ─── 加载器 ─────────────────────────────────────────────────

def load_config() -> dict:
    """加载 website/config.yml。"""
    if not CONFIG_PATH.exists():
        print(f"[WARN] 配置文件不存在: {CONFIG_PATH}，使用默认值")
        return {"site": {"title_zh": "学术主页", "title_en": "Academic Homepage"},
                "author": {}, "social": {}, "theme": {}, "nav": [], "homepage": {}}
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_vocab() -> dict:
    """加载受控词汇表。"""
    if not VOCAB_PATH.exists():
        return {"atom_types": [], "structure_tags": [], "skill_categories": [],
                "project_statuses": [], "atom_statuses": []}
    with open(VOCAB_PATH, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_atoms() -> list[dict]:
    """加载全部原子（跳过 example- 文件）。"""
    atoms = []
    if not ATOMS_DIR.is_dir():
        return atoms

    for f in sorted(ATOMS_DIR.rglob("*.md")):
        # 跳过示例文件
        if f.parent.stem == "example" or f.name.startswith("example-"):
            continue
        # 跳过 scripts 目录下的文件
        if f.parent.stem == "scripts":
            continue
        fm = parse_front_matter(str(f))
        if not fm:
            continue
        body = parse_body(str(f))
        # 提取纯文本预览（去 Markdown 符号，去标题行）
        body_preview = body.strip()
        body_preview = re.sub(r'^#.*$', '', body_preview, flags=re.MULTILINE)
        body_preview = re.sub(r'[#*_`>\[\]]', '', body_preview)
        body_preview = re.sub(r'\n{3,}', '\n\n', body_preview)
        body_preview = body_preview.strip()[:200]
        atom = {
            "id": fm.get("id", f.stem),
            "title": fm.get("title", f.stem),
            "type": fm.get("type", "unknown"),
            "tags": fm.get("tags", []),
            "project": fm.get("project", "uncategorized"),
            "status": fm.get("status", "draft"),
            "source": fm.get("source", ""),
            "created": fm.get("created", ""),
            "body": body,
            "body_preview": body_preview,
            "body_html": md_to_html(body),
            "script": fm.get("script", ""),
            "script_deps": fm.get("script_deps", []),
            "script_input": fm.get("script_input", ""),
            "script_input_desc": fm.get("script_input_desc", ""),
            "script_args": fm.get("script_args", ""),
        }
        atoms.append(atom)
    return atoms


def load_publications() -> list[dict]:
    """加载已发表论文（knowledge/publications/ 下的 .md 文件）。"""
    pubs = []
    if not PUBLICATIONS_DIR.is_dir():
        return pubs
    for f in sorted(PUBLICATIONS_DIR.glob("*.md")):
        if f.name.startswith("pub-template"):
            continue
        fm = parse_front_matter(str(f))
        if not fm:
            continue
        pubs.append({
            "id": fm.get("id", f.stem),
            "title": fm.get("title", f.stem),
            "type": fm.get("type", "journal"),
            "authors": fm.get("authors", []),
            "journal": fm.get("journal", ""),
            "year": fm.get("year", ""),
            "doi": fm.get("doi", ""),
            "arxiv": fm.get("arxiv", ""),
            "pdf": fm.get("pdf", ""),
            "abstract": fm.get("abstract", ""),
            "tags": fm.get("tags", []),
        })
    return pubs


def load_software() -> list[dict]:
    """加载软件项目（knowledge/software/ 下的 .md 文件）。"""
    sw_list = []
    if not SOFTWARE_DIR.is_dir():
        return sw_list
    for f in sorted(SOFTWARE_DIR.glob("*.md")):
        if f.name.startswith("sw-template"):
            continue
        fm = parse_front_matter(str(f))
        if not fm:
            continue
        sw_list.append({
            "id": fm.get("id", f.stem),
            "title": fm.get("title", f.stem),
            "description": fm.get("description", ""),
            "language": fm.get("language", ""),
            "repo": fm.get("repo", ""),
            "docs": fm.get("docs", ""),
            "license": fm.get("license", ""),
            "status": fm.get("status", "active"),
            "tags": fm.get("tags", []),
        })
    return sw_list


def load_skill_tree() -> dict:
    """解析技能树，返回 { 分类: [技能列表] }。"""
    categories = {}
    if not SKILL_TREE_PATH.exists():
        return categories

    content = SKILL_TREE_PATH.read_text(encoding="utf-8")
    lines = content.split("\n")

    current_category = "未分类"
    # 解析 ## 标题作为分类
    for line in lines:
        m = re.match(r"^##\s+(.+)", line)
        if m:
            current_category = m.group(1).strip()

    # 解析表格行
    current_category = "未分类"
    skill_rows = []
    in_table = False
    for line in lines:
        cm = re.match(r"^##\s+(.+)", line)
        if cm:
            if skill_rows:
                categories[current_category] = skill_rows
            current_category = cm.group(1).strip()
            skill_rows = []
            in_table = False
            continue

        # 检测表格行: | 技能 | 评级 | 证据 |
        if re.match(r"^\|\s*[^|]+\|\s*[^|]+\|\s*[^|]+\s*\|", line):
            cells = [c.strip() for c in line.split("|")[1:-1]]
            if len(cells) >= 3 and cells[0] not in ("技能", "------", ""):
                skill_rows.append({
                    "name": cells[0],
                    "level": cells[1] if cells[1] != "--" else "",
                    "evidence": cells[2] if len(cells) > 2 else "",
                })

    if skill_rows:
        categories[current_category] = skill_rows

    return categories


def load_matrix() -> dict | None:
    """解析 matrix.md，返回矩阵结构。"""
    if not MATRIX_PATH.exists():
        return None

    content = MATRIX_PATH.read_text(encoding="utf-8")

    # 去掉示例区域（## 使用示例 到下一个 ## 或文件尾）
    example_start = content.find("## 使用示例")
    if example_start > 0:
        next_section = content.find("\n## ", example_start + 1)
        if next_section > 0:
            content = content[:example_start] + content[next_section:]
        else:
            content = content[:example_start]

    # 找到第一个表格
    lines = content.split("\n")
    table_start = None
    for i, line in enumerate(lines):
        if line.startswith("|") and "-" in line:
            # 这是表头分隔行
            header_line = lines[i - 1] if i > 0 else ""
            if header_line.startswith("|"):
                table_start = i - 1
                break

    if table_start is None:
        return None

    # 提取表格行
    header_parts = [c.strip() for c in lines[table_start].split("|")[1:-1]]
    problems = header_parts[1:] if len(header_parts) > 1 else []
    domains = []
    rows = []

    for i in range(table_start + 2, len(lines)):
        line = lines[i]
        if not line.startswith("|"):
            break
        cells = [c.strip() for c in line.split("|")[1:-1]]
        if len(cells) < 2:
            continue
        domain = cells[0]
        if domain and not domain.startswith("<!--"):
            domains.append(domain)
            row = {"domain": domain, "cells": []}
            for j, cell in enumerate(cells[1:]):
                # 提取项目链接和状态
                proj_match = re.search(r"\[([^\]]+)\]\(([^)]+)\)", cell)
                status_match = re.search(r"([✅🔬✍️📤💡])", cell)
                row["cells"].append({
                    "raw": cell,
                    "project_id": proj_match.group(1) if proj_match else "",
                    "project_url": proj_match.group(2) if proj_match else "",
                    "status": status_match.group(1) if status_match else "",
                    "empty": cell.strip() in ("", "—", "-"),
                })
            rows.append(row)

    return {"problems": problems, "domains": domains, "rows": rows}


def load_projects() -> dict:
    """加载全部项目，按桶分类。"""
    projects = {"ideas": [], "active": [], "completed": []}
    if not PROJECTS_DIR.is_dir():
        return projects

    bucket_map = {"ideas": "ideas", "active": "active", "completed": "completed"}
    for bucket_key, bucket_name in bucket_map.items():
        bucket_dir = PROJECTS_DIR / bucket_name
        if not bucket_dir.is_dir():
            continue
        for proj_dir in sorted(bucket_dir.iterdir()):
            if not proj_dir.is_dir():
                continue
            idx = proj_dir / "index.md"
            if not idx.exists():
                continue
            fm = parse_front_matter(str(idx))
            if not fm:
                continue
            body = parse_body(str(idx))

            # 扫描报告 HTML 和数据目录
            reports = sorted([f.name for f in proj_dir.glob("report-*.html")])
            has_data_dir = (proj_dir / "data").is_dir()

            proj = {
                "id": fm.get("id", proj_dir.name),
                "title": fm.get("title", proj_dir.name),
                "status": fm.get("status", "idea"),
                "domain": fm.get("domain", ""),
                "problem": fm.get("problem", ""),
                "priority": fm.get("priority", "medium"),
                "created": fm.get("created", ""),
                "updated": fm.get("updated", ""),
                "description": body,
                "description_html": md_to_html(body),
                "url": f"/projects/{proj_dir.name}/",
                "dir_name": proj_dir.name,
                "reports": reports,
                "has_data_dir": has_data_dir,
            }
            projects[bucket_key].append(proj)

    return projects


def resolve_atom_type_name(type_key: str, lang: str) -> str:
    """获取原子类型的中英文名称。"""
    return T.get(lang, {}).get("atom_type_names", {}).get(type_key, type_key)


def resolve_project_status_name(status_key: str, lang: str) -> str:
    """获取项目状态的中英文名称。"""
    return T.get(lang, {}).get("project_status_names", {}).get(status_key, status_key)


def skill_level_int(level: str) -> int:
    """L1→25, L2→50, L3→75, L4→100"""
    mapping = {"L1": 25, "L2": 50, "L3": 75, "L4": 100}
    return mapping.get(level, 0)


# ─── 页面构建器 ─────────────────────────────────────────────

def build_site(lang: str, config: dict, atoms: list, skill_tree: dict,
               matrix: dict | None, projects: dict, vocab: dict,
               env: Environment) -> int:
    """构建指定语言版本的全站。返回生成的文件数。"""
    t = T.get(lang, T["zh"])
    pages_created = 0
    is_primary = lang == config.get("site", {}).get("lang_primary", "zh")
    prefix = "" if is_primary else f"{lang}/"

    mkdir = lambda p: (PUBLIC_DIR / p).mkdir(parents=True, exist_ok=True)

    # 基础上下文
    ctx = {
        "lang": lang,
        "lang_other": t["switch_label"],
        "lang_other_url": t["switch_url"],
        "config": config,
        "t": t,
        "vocab": vocab,
        "current_year": date.today().year,
        "is_primary": is_primary,
        "prefix": prefix,
    }

    # ── 首页 ──
    mkdir(prefix)
    index_ctx = {**ctx,
        "page_id": "index",
        "atoms": atoms[:config.get("homepage", {}).get("show_latest_atoms", 5)],
        "active_projects": projects.get("active", [])[:config.get("homepage", {}).get("show_featured_projects", 3)],
        "resolve_atom_type_name": resolve_atom_type_name,
    }
    _write_page("index.html", index_ctx, env, PUBLIC_DIR / prefix / "index.html")
    pages_created += 1

    # ── 研究领域 ──
    mkdir(prefix + "research")
    research_ctx = {**ctx, "page_id": "research", "matrix": matrix,
        "resolve_project_status_name": resolve_project_status_name}
    _write_page("research.html", research_ctx, env, PUBLIC_DIR / prefix / "research" / "index.html")
    pages_created += 1

    # ── 学术产出 ──
    mkdir(prefix + "outputs")
    pubs_data = load_publications()
    sw_data = load_software()
    research_atoms = [a for a in atoms if a["type"] in ("result", "method")]
    outputs_ctx = {**ctx, "page_id": "outputs",
        "publications": pubs_data,
        "software": sw_data,
        "research_atoms": research_atoms,
        "research_types": sorted(set(a["type"] for a in research_atoms)),
        "pub_types": sorted(set(p["type"] for p in pubs_data)),
        "resolve_atom_type_name": resolve_atom_type_name}
    _write_page("outputs.html", outputs_ctx, env, PUBLIC_DIR / prefix / "outputs" / "index.html")
    pages_created += 1

    # ── 项目 ──
    mkdir(prefix + "projects")
    projs_ctx = {**ctx, "page_id": "projects", "projects": projects,
        "resolve_project_status_name": resolve_project_status_name}
    _write_page("projects.html", projs_ctx, env, PUBLIC_DIR / prefix / "projects" / "index.html")
    pages_created += 1

    # 单个项目详情页
    for bucket_key in ("active", "completed", "ideas"):
        for proj in projects.get(bucket_key, []):
            proj_dir_name = proj["id"]
            mkdir(prefix + f"projects/{proj_dir_name}")
            proj_ctx = {**ctx, "page_id": "project", "project": proj,
                "bucket_key": bucket_key,
                "project_atoms": [a for a in atoms if a["project"] == proj["id"]],
                "resolve_atom_type_name": resolve_atom_type_name,
                "resolve_project_status_name": resolve_project_status_name}
            _write_page("project-single.html", proj_ctx, env,
                        PUBLIC_DIR / prefix / "projects" / proj_dir_name / "index.html")
            pages_created += 1

            # 复制项目报告 HTML 和 data/ 图片到网站输出
            _copy_project_assets(bucket_key, proj, prefix)

    # ── 能力 ──
    mkdir(prefix + "skills")
    skills_ctx = {**ctx, "page_id": "skills", "skill_tree": skill_tree,
        "skill_level_int": skill_level_int}
    _write_page("skills.html", skills_ctx, env, PUBLIC_DIR / prefix / "skills" / "index.html")
    pages_created += 1

    # ── 知识库 ──
    mkdir(prefix + "atoms")
    all_tags = sorted(set(tag for a in atoms for tag in a.get("tags", [])))
    all_types = sorted(set(a["type"] for a in atoms))
    atoms_ctx = {**ctx, "page_id": "atoms", "atoms": atoms,
        "all_tags": all_tags, "all_types": all_types,
        "resolve_atom_type_name": resolve_atom_type_name}
    _write_page("atoms.html", atoms_ctx, env, PUBLIC_DIR / prefix / "atoms" / "index.html")
    pages_created += 1

    # 单个原子详情页
    for atom in atoms:
        aid = atom["id"]
        mkdir(prefix + f"atoms/{aid}")
        atom_ctx = {**ctx, "page_id": "atom", "atom": atom,
            "resolve_atom_type_name": resolve_atom_type_name}
        _write_page("atom-single.html", atom_ctx, env,
                    PUBLIC_DIR / prefix / "atoms" / aid / "index.html")
        pages_created += 1

    return pages_created


def _copy_project_assets(bucket: str, proj: dict, prefix: str):
    """复制项目的报告 HTML 和 data/ 目录到网站输出。"""
    proj_src = PROJECTS_DIR / bucket / proj["dir_name"]
    proj_dst = PUBLIC_DIR / prefix / "projects" / proj["dir_name"]

    # 复制 report-*.html
    for rpt in proj.get("reports", []):
        rpt_src = proj_src / rpt
        if rpt_src.exists():
            shutil.copy2(str(rpt_src), str(proj_dst / rpt))
            print(f"     📄 报告: {proj['dir_name']}/{rpt}")

    # 复制 data/ 目录（图片等）
    data_src = proj_src / "data"
    if data_src.is_dir():
        data_dst = proj_dst / "data"
        shutil.copytree(str(data_src), str(data_dst), dirs_exist_ok=True)
        n_files = len(list(data_dst.rglob("*")))
        print(f"     🖼️  图片: {proj['dir_name']}/data/ ({n_files} 个文件)")


def _write_page(template_name: str, context: dict, env: Environment, output_path: Path):
    """渲染模板并写入文件。"""
    try:
        template = env.get_template(template_name)
        html = template.render(**context)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(html, encoding="utf-8")
    except Exception as e:
        print(f"[ERROR] 渲染 {template_name} → {output_path}: {e}")
        import traceback
        traceback.print_exc()


# ─── 主入口 ─────────────────────────────────────────────────

def main():
    args = set(sys.argv[1:])
    serve = "--serve" in args
    lang_filter = None
    for a in args:
        if a.startswith("--lang="):
            lang_filter = a.split("=", 1)[1]

    print("=" * 56)
    print("  AOS Website Builder — 中英文双语学术网站")
    print("=" * 56)
    print()

    # 1. 加载配置
    config = load_config()
    print(f"  📄 配置已加载: {CONFIG_PATH.name}")

    # 2. 加载 AOS 数据
    vocab = load_vocab()
    atoms = load_atoms()
    skill_tree = load_skill_tree()
    matrix = load_matrix()
    projects = load_projects()

    print(f"  📦 原子: {len(atoms)}")
    print(f"  📁 项目: {sum(len(v) for v in projects.values())}")
    print(f"  🗂️  矩阵: {'✅' if matrix else '❌ 未配置'}")
    print(f"  💪 技能分类: {len(skill_tree)}")
    print()

    # 3. 清理输出目录
    if PUBLIC_DIR.exists():
        shutil.rmtree(PUBLIC_DIR)
    PUBLIC_DIR.mkdir(parents=True)

    # 4. 复制静态资源
    static_target = PUBLIC_DIR / "static"
    if STATIC_DIR.exists():
        shutil.copytree(STATIC_DIR, static_target, dirs_exist_ok=True)
    print(f"  🎨 静态资源已复制")

    # 5. 设置 Jinja2，注册全局函数
    env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))
    env.globals["resolve_atom_type_name"] = resolve_atom_type_name
    env.globals["resolve_project_status_name"] = resolve_project_status_name
    env.globals["skill_level_int"] = skill_level_int

    # 6. 构建各语言版本
    languages = ["zh", "en"] if not lang_filter else [lang_filter]
    total_pages = 0
    for lang in languages:
        print(f"\n  🌐 构建语言: {'中文' if lang == 'zh' else 'English'} ({lang})")
        n = build_site(lang, config, atoms, skill_tree, matrix, projects, vocab, env)
        total_pages += n
        print(f"     → {n} 个页面")

    # 7. 确保 /en/ 下的静态资源也被正确引用（已有 static 在根目录，通过相对路径引用即可）
    print(f"\n  📊 总计: {total_pages} 个页面生成")
    print(f"  📂 输出目录: {PUBLIC_DIR.resolve()}")
    print()

    # 8. 写入构建信息
    build_info = {
        "built_at": date.today().isoformat(),
        "langs": languages,
        "pages": total_pages,
        "atoms": len(atoms),
        "projects": sum(len(v) for v in projects.values()),
    }
    (PUBLIC_DIR / "build-info.json").write_text(
        json.dumps(build_info, indent=2, ensure_ascii=False), encoding="utf-8")

    # 9. 写入 .nojekyll（GitHub Pages 兼容）
    (PUBLIC_DIR / ".nojekyll").write_text("")

    print("  ✅ 构建完成！")

    # 10. --watch 模式：监听文件变化自动重建
    if "--watch" in args:
        _start_watch(config, vocab, env)

    if serve:
        print("\n  启动本地预览: http://localhost:8000")
        os.chdir(str(PUBLIC_DIR))
        subprocess.run([sys.executable, "-m", "http.server", "8000"])
    else:
        print("  预览: cd website/public && python -m http.server 8000")


def _get_watch_paths() -> list[Path]:
    """返回需要监听的文件列表。"""
    paths = []
    paths.append(CONFIG_PATH)
    paths.append(MATRIX_PATH)
    paths.append(SKILL_TREE_PATH)
    paths.append(VOCAB_PATH)
    if TEMPLATES_DIR.is_dir():
        paths.extend(sorted(TEMPLATES_DIR.rglob("*.html")))
    if STATIC_DIR.is_dir():
        paths.extend(sorted(STATIC_DIR.rglob("*")))
    if ATOMS_DIR.is_dir():
        paths.extend(sorted(ATOMS_DIR.rglob("*.md")))
    if PROJECTS_DIR.is_dir():
        for p in PROJECTS_DIR.rglob("*.md"):
            if "index.md" in str(p):
                paths.append(p)
    return [p for p in paths if p.exists()]


def _get_mtime_map(paths: list[Path]) -> dict[str, float]:
    """返回 {str(path): mtime} 映射。"""
    return {str(p): p.stat().st_mtime for p in paths}


def _start_watch(config: dict, vocab: dict, env: Environment):
    """文件监听循环，检测到变化后自动重建。"""
    print("\n  👀 监听模式已启动 (Ctrl+C 停止)")
    print("     监听范围: config.yml / 模板 / CSS / 原子 / 项目 / 矩阵 / 技能树\n")

    watch_paths = _get_watch_paths()
    mtime_map = _get_mtime_map(watch_paths)
    poll_interval = 1.5  # 秒

    import time as _time
    try:
        while True:
            _time.sleep(poll_interval)
            changed = []
            for p in watch_paths:
                if not p.exists():
                    continue
                current = p.stat().st_mtime
                if abs(current - mtime_map.get(str(p), 0)) > 0.01:
                    changed.append(p)
                    mtime_map[str(p)] = current

            if changed:
                print(f"\n  🔄 检测到 {len(changed)} 个文件变化，重新构建...")
                for c in changed[:5]:
                    print(f"     {c.relative_to(ROOT)}")
                if len(changed) > 5:
                    print(f"     ...及其他 {len(changed) - 5} 个")

                # 更新路径列表（可能有新增文件）
                watch_paths = _get_watch_paths()
                mtime_map = _get_mtime_map(watch_paths)

                # 重建
                _do_rebuild(config, vocab, env)
    except KeyboardInterrupt:
        print("\n  👋 监听已停止")


def _do_rebuild(config, vocab, env):
    """执行一次完整重建。"""
    try:
        from datetime import date as _date

        # 重新加载数据
        atoms = load_atoms()
        skill_tree = load_skill_tree()
        matrix = load_matrix()
        projects = load_projects()

        # 清理并重新构建
        if PUBLIC_DIR.exists():
            shutil.rmtree(PUBLIC_DIR)
        PUBLIC_DIR.mkdir(parents=True)

        static_target = PUBLIC_DIR / "static"
        if STATIC_DIR.exists():
            shutil.copytree(STATIC_DIR, static_target, dirs_exist_ok=True)

        languages = ["zh", "en"]
        total = 0
        for lang in languages:
            n = build_site(lang, config, atoms, skill_tree, matrix, projects, vocab, env)
            total += n

        (PUBLIC_DIR / ".nojekyll").write_text("")
        build_info = {
            "built_at": _date.today().isoformat(),
            "langs": languages, "pages": total,
            "atoms": len(atoms), "projects": sum(len(v) for v in projects.values()),
        }
        (PUBLIC_DIR / "build-info.json").write_text(
            json.dumps(build_info, indent=2, ensure_ascii=False))

        print(f"  ✅ 重建完成 — {total} 个页面 ({_date.today().isoformat()})")
    except Exception as e:
        print(f"  ❌ 重建失败: {e}")
        import traceback
        traceback.print_exc()


if __name__ == "__main__":
    main()
